/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 scene.gltf 
Author: asads (https://sketchfab.com/asads)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/box-d919737a5a5b464f809d12f7e1fad78f
Title: Box
*/

import { useGLTF } from '@react-three/drei'

export function BoxModel(props) {
  const { nodes, materials } = useGLTF('/models/box/scene.gltf')
  return (
    <group {...props} dispose={null} scale={0.025}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-3.799, -0.08, 0]}>
          <group position={[3.799, 0.08, 0]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials['01_-_Default']} />
            <mesh geometry={nodes.Object_5.geometry} material={materials['01_-_Defaultddd']} />
          </group>
        </group>
      </group>
    </group>
  )
}

