/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 scene.gltf 
Author: Haydn_Brown (https://sketchfab.com/Haydn_Brown)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pallet-racking-68e7aab6eb7a441fbfe2d7505cc44aca
Title: Pallet Racking
*/

import { useGLTF } from '@react-three/drei'

export function RackModel(props) {
  const { nodes, materials } = useGLTF('/models/rack/scene.gltf')
  return (
    <group {...props} dispose={null} scale={4}>
      <group position={[0, 0.295, 0.515]} rotation={[0, Math.PI / 2, 0]} scale={[1, 1, 2.419]}>
        <mesh geometry={nodes.Object_8.geometry} material={materials.Orange_Metal} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Material} position={[0.515, 0.065, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[0.517, 0.019, 0.54]} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Mesh_Metal} position={[0.515, 0.03, -0.341]} rotation={[0, -Math.PI / 2, 0]} scale={[0.165, 0.019, 0.54]} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Mesh_Metal} position={[0.515, 0.03, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[0.165, 0.019, 0.54]} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Mesh_Metal} position={[0.515, 0.03, 0.341]} rotation={[0, -Math.PI / 2, 0]} scale={[0.165, 0.019, 0.54]} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.Orange_Metal} position={[0.515, 0.065, 0.341]} rotation={[0, -Math.PI / 2, 0]} scale={[0.165, 0.019, 0.54]} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.Orange_Metal} position={[0.515, 0.065, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[0.165, 0.019, 0.54]} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.Orange_Metal} position={[0.515, 0.065, -0.341]} rotation={[0, -Math.PI / 2, 0]} scale={[0.165, 0.019, 0.54]} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.Mesh_Metal} position={[0.515, 0.035, -0.341]} rotation={[0, -Math.PI / 2, 0]} scale={[0.413, 1, 1]} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.Mesh_Metal} position={[0.515, 0.035, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[0.413, 1, 1]} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.Mesh_Metal} position={[0.515, 0.035, 0.341]} rotation={[0, -Math.PI / 2, 0]} scale={[0.413, 1, 1]} />
      </group>
      <group position={[0, 1.395, 0.515]} rotation={[0, Math.PI / 2, 0]} scale={[1, 1, 2.419]}>
        <mesh geometry={nodes.Object_30.geometry} material={materials.Orange_Metal} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.Material} position={[0.515, 0.065, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[0.517, 0.019, 0.54]} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.Mesh_Metal} position={[0.515, 0.03, -0.341]} rotation={[0, -Math.PI / 2, 0]} scale={[0.165, 0.019, 0.54]} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.Mesh_Metal} position={[0.515, 0.03, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[0.165, 0.019, 0.54]} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.Mesh_Metal} position={[0.515, 0.03, 0.341]} rotation={[0, -Math.PI / 2, 0]} scale={[0.165, 0.019, 0.54]} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.Orange_Metal} position={[0.515, 0.065, 0.341]} rotation={[0, -Math.PI / 2, 0]} scale={[0.165, 0.019, 0.54]} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.Orange_Metal} position={[0.515, 0.065, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[0.165, 0.019, 0.54]} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.Orange_Metal} position={[0.515, 0.065, -0.341]} rotation={[0, -Math.PI / 2, 0]} scale={[0.165, 0.019, 0.54]} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.Mesh_Metal} position={[0.515, 0.035, -0.341]} rotation={[0, -Math.PI / 2, 0]} scale={[0.413, 1, 1]} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.Mesh_Metal} position={[0.515, 0.035, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[0.413, 1, 1]} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.Mesh_Metal} position={[0.515, 0.035, 0.341]} rotation={[0, -Math.PI / 2, 0]} scale={[0.413, 1, 1]} />
      </group>
      <group position={[0, 2.495, 0.515]} rotation={[0, Math.PI / 2, 0]} scale={[1, 1, 2.419]}>
        <mesh geometry={nodes.Object_52.geometry} material={materials.Orange_Metal} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.Material} position={[0.515, 0.065, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[0.517, 0.019, 0.54]} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.Mesh_Metal} position={[0.515, 0.03, -0.341]} rotation={[0, -Math.PI / 2, 0]} scale={[0.165, 0.019, 0.54]} />
        <mesh geometry={nodes.Object_58.geometry} material={materials.Mesh_Metal} position={[0.515, 0.03, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[0.165, 0.019, 0.54]} />
        <mesh geometry={nodes.Object_60.geometry} material={materials.Mesh_Metal} position={[0.515, 0.03, 0.341]} rotation={[0, -Math.PI / 2, 0]} scale={[0.165, 0.019, 0.54]} />
        <mesh geometry={nodes.Object_62.geometry} material={materials.Orange_Metal} position={[0.515, 0.065, 0.341]} rotation={[0, -Math.PI / 2, 0]} scale={[0.165, 0.019, 0.54]} />
        <mesh geometry={nodes.Object_64.geometry} material={materials.Orange_Metal} position={[0.515, 0.065, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[0.165, 0.019, 0.54]} />
        <mesh geometry={nodes.Object_66.geometry} material={materials.Orange_Metal} position={[0.515, 0.065, -0.341]} rotation={[0, -Math.PI / 2, 0]} scale={[0.165, 0.019, 0.54]} />
        <mesh geometry={nodes.Object_68.geometry} material={materials.Mesh_Metal} position={[0.515, 0.035, -0.341]} rotation={[0, -Math.PI / 2, 0]} scale={[0.413, 1, 1]} />
        <mesh geometry={nodes.Object_70.geometry} material={materials.Mesh_Metal} position={[0.515, 0.035, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[0.413, 1, 1]} />
        <mesh geometry={nodes.Object_72.geometry} material={materials.Mesh_Metal} position={[0.515, 0.035, 0.341]} rotation={[0, -Math.PI / 2, 0]} scale={[0.413, 1, 1]} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Blue_Metal} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.Blue_Metal} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Plain_Metal} />
    </group>
  )
}

